"""correccion_nombre_foreneas

Revision ID: 45bdc2ec0c93
Revises: 71449c43c298
Create Date: 2021-09-25 11:21:47.276919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45bdc2ec0c93'
down_revision = '71449c43c298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispositivo', sa.Column('tipo_dispositivo_id', sa.Integer(), nullable=False))
    op.drop_constraint('dispositivo_ibfk_3', 'dispositivo', type_='foreignkey')
    op.create_foreign_key(None, 'dispositivo', 'detalle', ['tipo_dispositivo_id'], ['id'])
    op.drop_column('dispositivo', 'tipo_dispositivo')
    op.add_column('empresa', sa.Column('tipo_identificacion_id', sa.Integer(), nullable=False))
    op.drop_constraint('empresa_ibfk_1', 'empresa', type_='foreignkey')
    op.create_foreign_key(None, 'empresa', 'detalle', ['tipo_identificacion_id'], ['id'])
    op.drop_column('empresa', 'tipo_identificacion')
    op.add_column('referencia_unidad', sa.Column('tipo_unidad_id', sa.Integer(), nullable=False))
    op.drop_constraint('referencia_unidad_ibfk_2', 'referencia_unidad', type_='foreignkey')
    op.create_foreign_key(None, 'referencia_unidad', 'detalle', ['tipo_unidad_id'], ['id'])
    op.drop_column('referencia_unidad', 'tipo_unidad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referencia_unidad', sa.Column('tipo_unidad', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'referencia_unidad', type_='foreignkey')
    op.create_foreign_key('referencia_unidad_ibfk_2', 'referencia_unidad', 'detalle', ['tipo_unidad'], ['id'])
    op.drop_column('referencia_unidad', 'tipo_unidad_id')
    op.add_column('empresa', sa.Column('tipo_identificacion', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'empresa', type_='foreignkey')
    op.create_foreign_key('empresa_ibfk_1', 'empresa', 'detalle', ['tipo_identificacion'], ['id'])
    op.drop_column('empresa', 'tipo_identificacion_id')
    op.add_column('dispositivo', sa.Column('tipo_dispositivo', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dispositivo', type_='foreignkey')
    op.create_foreign_key('dispositivo_ibfk_3', 'dispositivo', 'detalle', ['tipo_dispositivo'], ['id'])
    op.drop_column('dispositivo', 'tipo_dispositivo_id')
    # ### end Alembic commands ###
