"""tablas_mesa_ayuda

Revision ID: 71449c43c298
Revises: 943e46974e08
Create Date: 2021-09-25 11:12:30.864872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71449c43c298'
down_revision = '943e46974e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alquiler',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('fecha_cohorte', sa.Date(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sede.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud_servicio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('radicado', sa.String(length=100), nullable=False),
    sa.Column('fecha_solicitud', sa.Date(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=True),
    sa.Column('solicitante', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('tipo_solicitud_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_requerimiento', sa.String(length=300), nullable=False),
    sa.Column('tipo_cliente_id', sa.Integer(), nullable=False),
    sa.Column('recibio_solicitud_id', sa.Integer(), nullable=False),
    sa.Column('medio_solicitud_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['detalle.id'], ),
    sa.ForeignKeyConstraint(['medio_solicitud_id'], ['detalle.id'], ),
    sa.ForeignKeyConstraint(['recibio_solicitud_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['tipo_cliente_id'], ['detalle.id'], ),
    sa.ForeignKeyConstraint(['tipo_solicitud_id'], ['detalle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atencion_solicitud',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solicitud_servicio_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('descripcion_solucion', sa.String(length=300), nullable=True),
    sa.Column('fecha_realizacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_servicio_id'], ['solicitud_servicio.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atencion_solicitud')
    op.drop_table('solicitud_servicio')
    op.drop_table('alquiler')
    # ### end Alembic commands ###
