"""tablas bodega

Revision ID: 943e46974e08
Revises: 2d3947c75735
Create Date: 2021-09-24 14:18:27.629343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943e46974e08'
down_revision = '2d3947c75735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('limite_contador', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['detalle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispositivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial', sa.String(length=200), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=False),
    sa.Column('tipo_dispositivo', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['detalle.id'], ),
    sa.ForeignKeyConstraint(['referencia_id'], ['referencia.id'], ),
    sa.ForeignKeyConstraint(['tipo_dispositivo'], ['detalle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referencia_unidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_unidad', sa.Integer(), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['referencia_id'], ['referencia.id'], ),
    sa.ForeignKeyConstraint(['tipo_unidad'], ['detalle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impresora',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_contador', sa.Date(), nullable=False),
    sa.Column('contador', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivo.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['detalle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impresora_unidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('impresora_id', sa.Integer(), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=False),
    sa.Column('contador', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['impresora_id'], ['impresora.id'], ),
    sa.ForeignKeyConstraint(['unidad_id'], ['detalle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impresora_unidad')
    op.drop_table('impresora')
    op.drop_table('referencia_unidad')
    op.drop_table('dispositivo')
    op.drop_table('referencia')
    # ### end Alembic commands ###
